### Exercises cover both Exception Handling and variable scopes.


### Q1) Run the following programs, identify and Fix the errors.
Use **exception handling** approach to handle the erros.


In [ ]:
#Q1.1) Zero division error
def myfunction(a,b):
    if b == 0:
        print("Error: Cannot divide by zero!")
        return None
    else:
        answer = a/b
        return answer

print(myfunction(2,0))
print(myfunction(10,2))

Error: Cannot divide by zero!
None
5.0


In [ ]:
#Q1.2 Name Error

def myfunction2(a, c):
    answer = a/c
    return answer


# Call the function as follows:
myfunction2(6, 3)

2.0

In [ ]:
#Q1.3 IndexError
def myfunction3(b):
    mylist = [2, 3, 5, -7, 8, 0]
    idx = 0
    while idx < len(mylist): # Fixed: Changed condition from idx<=6 to idx < len(mylist) to prevent IndexError
        print('Iteration:', idx, mylist[idx]/b)
        idx = idx+1
        print('Iteration completed')

# Call the function as follows:
myfunction3(b=5)

Iteration: 0 0.4
Iteration completed
Iteration: 1 0.6
Iteration completed
Iteration: 2 1.0
Iteration completed
Iteration: 3 -1.4
Iteration completed
Iteration: 4 1.6
Iteration completed
Iteration: 5 0.0
Iteration completed


In [ ]:
#Q1.4 Zero Division Error, Value Error
def divide(a, b):
    if not isinstance(a, (int, float)) or not isinstance(b, (int, float)):
        print('Error: Both inputs must be numbers.')
        return None
    if b == 0:
        print('Error: Cannot divide by zero!')
        return None
    result = a / b
    print('The result of division is', result)
    return result


# Call the function as follows:
divide("10",2)
divide(10,0)
divide(10, "two")

Error: Both inputs must be numbers.
Error: Cannot divide by zero!
Error: Both inputs must be numbers.


In [ ]:
#Q1.5 FileNotFoundError
def read_file(filename):
    with open(filename, 'r') as file1:
        word_string = file1.read()
    print("File reading completed successfully")
    # FIX THE ERROR BELOW
    # FileNotFoundError
    return word_string


# Call the function as follows:
read_file("Q1.txt")

File reading completed successfully


'This is a test file for Q1.5.'

### Q2) Run the following programs and fix the errors.
Check the scopes of the variable, and fix it.

In [ ]:
def check_rows(grid, expected_numbers):
    """Checks for uniqueness and completeness (1-9) in every row."""
    for i, row in enumerate(grid):
        if set(row) != expected_numbers:
            return False, f"Row {i + 1}: {row}"
    return True, None

def check_cols(grid, expected_numbers, sudoku_size):
    """Checks for uniqueness and completeness (1-9) in every column."""
    for j in range(sudoku_size):
        column = [grid[i][j] for i in range(sudoku_size)]
        if set(column) != expected_numbers:
            return False, f"Column {j + 1}: {column}"
    return True, None

def check_blocks(grid, expected_numbers, sudoku_size):
    """Checks for uniqueness and completeness (1-9) in every 3x3 block."""
    block_size = int(sudoku_size**0.5) # For 9x9, this is 3
    # Iterate over the starting indices for the blocks
    for block_row_start in range(0, sudoku_size, block_size):
        for block_col_start in range(0, sudoku_size, block_size):
            block = []

            # Extract the block's elements
            for i in range(block_row_start, block_row_start + block_size):
                for j in range(block_col_start, block_col_start + block_size):
                    block.append(grid[i][j])

            # Check for uniqueness and completeness (1-9)
            if set(block) != expected_numbers:
                return False, f"Block at ({block_row_start+1}, {block_col_start+1})"
    return True, None

def is_sudoku_solved(grid):
    """
    Checks if the given 9x9 grid is a correctly solved Sudoku puzzle by verifying
    row, column, and 3x3 block constraints.
    """
    sudoku_size = len(grid)
    # 1. Basic check: Ensure the grid is square
    if sudoku_size == 0 or any(len(row) != sudoku_size for row in grid):
        print("Error: Grid must be a square.")
        return False

    # Sudoku constraints for standard 9x9 imply numbers 1-9
    if sudoku_size != 9:
        print("Warning: This function is designed for 9x9 Sudoku grids (1-9).")
        # For a more general solution, expected_numbers would be range(1, sudoku_size + 1)
        # and block_size would need to be checked if it's a perfect square root.

    expected_numbers = set(range(1, sudoku_size + 1))

    # 2. Check Rows
    is_valid, error_info = check_rows(grid, expected_numbers)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # 3. Check Columns
    is_valid, error_info = check_cols(grid, expected_numbers, sudoku_size)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # 4. Check Blocks
    is_valid, error_info = check_blocks(grid, expected_numbers, sudoku_size)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # If all checks pass, the Sudoku is solved correctly
    return True

# calling the function as follows:

import numpy as np
grid = np.random.randint(1,10,(9,9))
print(grid)
is_sudoku_solved(grid.tolist())

solved_grid = [
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
]
is_sudoku_solved(solved_grid)

[[6 4 1 5 1 4 4 3 5]
 [2 5 1 5 4 8 8 8 7]
 [9 7 8 2 2 5 4 5 8]
 [2 4 8 8 6 5 9 3 6]
 [3 7 9 6 5 1 7 2 8]
 [4 1 6 7 1 7 7 5 8]
 [1 7 5 5 4 4 7 8 4]
 [8 1 5 1 7 2 4 4 6]
 [9 7 8 4 9 2 4 2 1]]
Mistake found in Row 1: [6, 4, 1, 5, 1, 4, 4, 3, 5]


True